# Generated by Django 6.1 on 2026-08-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('child_name', models.CharField(max_length=100)),
                ('target_class', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('FOLLOW_UP', 'À relancer'), ('CLOSED', 'Fermée/Inscrit')], default='OPEN', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('purpose', models.TextField()),
                ('person_to_meet', models.CharField(max_length=100)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
