# Generated by Django 6.1 on 2026-08-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=150, verbose_name='Spécialisation'),
        ),
    ]
