# Generated by Django 6.1 on 2026-08-26 18:45

import django.db.models.deletion
import documents.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/', validators=[documents.validators.validate_file_extension, documents.validators.validate_file_size])),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('target_role', models.CharField(choices=[('ALL', 'Tous'), ('STUDENT', 'Élèves'), ('TEACHER', 'Enseignants'), ('PARENT', 'Parents')], default='ALL', max_length=20)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
