# Generated by Django 6.1 on 2026-08-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='level',
            field=models.IntegerField(choices=[(1, 'Année 1'), (2, 'Année 2'), (3, 'Année 3'), (4, 'Année 4'), (5, 'Année 5'), (6, 'Année 6'), (7, 'Année 7'), (8, 'Année 8'), (9, 'Année 9'), (10, 'Année 10'), (11, 'Année 11'), (12, 'Année 12')], default=1, verbose_name="Niveau d'année (1-12)"),
        ),
    ]
