# Generated by Django 6.1 on 2026-08-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_schoolclass_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='section',
            field=models.CharField(blank=True, max_length=10, verbose_name='Section / Groupe (ex: A, B, C)'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom complet (Optionnel)'),
        ),
    ]
